### ISSUE TITLE
Nugetitization

### ISSUE THREAD

**Issue by Eibwen** [Puchaczov/Musoq#2]
I wondered if you'd like any attempt at help on making nuget files out of your projects here.  I've not looked at your code too much, but I imagine each "plugin" requires quite different dependencies, which I as a consumer you wouldn't want to require me to import, meaning we'd want a separate nuget for each plugin.

Let me know if you'd appreciate me taking a stab at setting that up (if I had any free time to do so) and/or reviewing any nuget packaging setup you work on

**Comment by Puchaczov** [comment]
Thank you for posting the first issue :)

I'm thinking of "nugetizing" it since long time. Basically, as a consumer to produce the plugin, the only what you need to include is Musoq.Schema.dll and Musoq.Plugins.dll. I will deffinitivelly appreciate any work you do to configure the project, then I will publish those packages to Nuget service.

**Comment by Puchaczov** [comment]
**Musoq.Plugins** and **Musoq.Schema** can be downloaded by **Nuget** so you have the ability to create plugins without having downloaded other parts of project.

Just type "Musoq" in nuget.
