### ISSUE TITLE
Zip Slip vulnerability

### ISSUE THREAD

**Issue by xcorail** [Puchaczov/Musoq#5]
Hi

[LGTM](lgtm.com) has discovered potential occurrences of the Zip Slip vulnerability. The alerts are available [here](https://lgtm.com/projects/g/Puchaczov/Musoq/snapshot/dist-1506485459480-1538135180039/files/Musoq.Schema.Os/Zip/SchemaZipHelper.cs?sort=name&dir=ASC&mode=heatmap&showExcluded=true#V49)

For more details about the problem: https://lgtm.com/rules/1506511188430/
Best regards

**Comment by Puchaczov** [comment]
Thank you for your contribution, I will prepare appropriate fix to resolve this vulnerability.

**Comment by sjvs** [comment]
It looks like this was fixed in [4b45fbb33ab62d13f94385e73113ff3b65985359](https://github.com/Puchaczov/Musoq/commit/4b45fbb33ab62d13f94385e73113ff3b65985359). Great stuff.

Glad to see that the LGTM.com alerts are useful. If you're interested, there are some more here: https://lgtm.com/projects/g/Puchaczov/Musoq/alerts

LGTM also offers automated code review for pull requests. You can use that to make sure issues like these never actually get merged into master. Here's an example of how AMPHTML use that: https://github.com/ampproject/amphtml/pull/13060. You can enable it for Musoq here: https://lgtm.com/projects/g/Puchaczov/Musoq/ci.

**Comment by Puchaczov** [comment]
Thank you, I have fixed some of them already but others still needs to be resolved. Anyway I will close the issue and try to fixed others in next commits.
